name: saturn
channels:
- defaults
- pytorch
- saturncloud
- conda-forge
dependencies:
- blas=*=mkl
- bokeh
- dask-ml
- dask-saturn==0.0.4
- dask-xgboost
- dask==2.20.0
- datashader
- distributed==2.20.0
- fastparquet
- firefox
- geckodriver
- geopandas
- geoviews
- graphviz
- hvplot
- ipykernel
- ipywidgets
- matplotlib
- numba
- numpy
- pandas=1.0.5
- panel
- pip
- prefect
- pyarrow
- python=3.7
- s3fs
- scikit-learn
- scipy
- selenium
- xgboost==0.90
